version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: rabbitmq-demo-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rabbitmq-demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-demo-mq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7
    container_name: rabbitmq-demo-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
